<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Make_Paragraph_To_Start_On_New_Page</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<None Update="Output\.gitkeep">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.DocIO.Net.Core" Version="*" />
  </ItemGroup>



</Project>
