
using System;
using System.Windows.Forms;

namespace Open_and_save_Word_document
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private Button btnOpenAndSave;
        private Label label;

        private void InitializeComponent()
        {
            label = new Label();
            btnOpenAndSave = new Button();

            //Label
            label.Location = new System.Drawing.Point(0, 40);
            label.Size = new System.Drawing.Size(426, 35);
            label.Text = "Click the button to view a Word document generated by Essential DocIO. Please note that Microsoft Word Viewer or Microsoft Word is required to view the resultant Word document";
            label.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            //Button
            btnOpenAndSave.Location = new System.Drawing.Point(180, 110);
            btnOpenAndSave.Size = new System.Drawing.Size(85, 36);
            btnOpenAndSave.Text = "Open and Save Document";
            btnOpenAndSave.Click += new EventHandler(btnOpenAndSave_Click);

            //Create Word
            ClientSize = new System.Drawing.Size(450, 150);
            Controls.Add(label);
            Controls.Add(btnOpenAndSave);
            Text = "Open and Save Word";
        }

        #endregion
    }
}

