using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using System;
using System.Drawing;
using System.Windows.Forms;

namespace Convert_Word_Document_to_Image
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private Button btnCreate;
        private Label label;
        private void InitializeComponent()
        {
            this.label = new System.Windows.Forms.Label();
            this.btnCreate = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // label
            // 
            this.label.Location = new System.Drawing.Point(0, 40);
            this.label.Name = "label";
            this.label.Size = new System.Drawing.Size(426, 35);
            this.label.TabIndex = 0;
            this.label.Text = "Click the button to Convert Word document to Image generated by Essential DocIO";
            this.label.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // btnCreate
            // 
            this.btnCreate.Location = new System.Drawing.Point(90, 110);
            this.btnCreate.Name = "btnCreate";
            this.btnCreate.Size = new System.Drawing.Size(223, 36);
            this.btnCreate.TabIndex = 1;
            this.btnCreate.Text = "Convert Word to Image";
            this.btnCreate.Click += new System.EventHandler(this.btnConvert_Click);
            // 
            // Form1
            // 
            this.ClientSize = new System.Drawing.Size(450, 150);
            this.Controls.Add(this.label);
            this.Controls.Add(this.btnCreate);
            this.Name = "Form1";
            this.Text = "Convert Word document to Image";
            this.ResumeLayout(false);

        }

        #endregion
    }
}

