<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Sign_multiple_signature_lines</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Syncfusion.DocIO.Net.Core" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Data\Template.docx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Data\certificate.pfx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Data\TonySignature.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Data\SteveSignature.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Data\BruceSignature.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Output\.gitkeep">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
